In [2]:
import numpy as np



In [11]:
#setting range 100 to  200 with diff of 5
x=np.arange(100,200,5)


In [12]:
x

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [14]:
x[0:16]

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175])

In [15]:
x[0:16].reshape(8,2)

array([[100, 105],
       [110, 115],
       [120, 125],
       [130, 135],
       [140, 145],
       [150, 155],
       [160, 165],
       [170, 175]])